theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relativ_links:
   enabled: true
   collections: true
include:
  - CONTRIBUTING.md
  - LICENCE.,md
  - INDEX.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUES_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
